### ISSUE TITLE
Login page: Chrome on iOS complains about non-secure images

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-cas-5#14]
I see this on my iPhone:

![image](https://user-images.githubusercontent.com/532845/38652485-85d4e8e6-3e49-11e8-84bc-6f0ea055667b.png)
 
This is just a check in case the new version has the same issue.

**Comment by sbearcsiro** [comment]
You can try it via https://auth-test.ala.org.au/cas

**Comment by nickdos** [comment]
Don't get errors so closing.
