### ISSUE TITLE
Log user login events

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-cas-5#16]
We would like to able to see how often users login to the ALA, so we need to log/track login events and possibly more (activity, etc)? Not sure where to store this data but could be in `userDetails` or `ELK` or Google Analytics (privacy issues probably rule this out).

Would be nice to see the number of logins in userDetails in admin view, and to be able to extract data via WS, etc.

**Comment by sbearcsiro** [comment]
CAS writes all events to an audit log, should be available via ELK already
